FROM oven/bun:1

WORKDIR /user/src/app

COPY ./package.json ./package.json
COPY ./packages ./packages

COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

COPY ./apps/backend ./apps/backend

RUN bun install
RUN apt-get update && apt-get install -y openssl
RUN bun run  db:generate

EXPOSE 8080

CMD ["bun","run", "start:backend"]




