name: deploying backend to ec2 machine 
on : 
  push :
    branches : 
      - main

jobs : 
    build-backend:
      runs-on : ubuntu-latest
      steps : 
        - uses : actions/checkout@v4
          with:
            fetch-depth : 0
        
        - name: Docker login
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name : Build and push Docker image 
          uses : docker/build-push-action@v4
          with :
            context : .
            file : ./docker/dockerfile.backend
            push : true
            tags : bideshmukhi/autoscaling_backend:${{ github.sha }}
            build-args : |
             DATABASE_URL=${{ secrets.DATABASE_URL }}
        - run : |
              echo "pulling docker image and re deoploying to ec2"
              echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
              mkdir ~/.ssh
              echo "${{ secrets.KNOWN_HOST }}" &> ~/.ssh/known_hosts
              chmod 700 /home/runner/ssh_key
              ssh  -i ~/ssh_key ubuntu@ec2-34-230-52-123.compute-1.amazonaws.com  " 
              docker stop backend || true  &&
              docker rm backend || true &&
              docker pull bideshmukhi/autoscaling_backend:${{ github.sha }} &&
              docker run -d -p 8080:8080 --name backend  bideshmukhi/autoscaling_backend:${{ github.sha }} &&
              docker image rm -f $(docker images -a | grep -v "your_image" | awk 'NR>1 {print $3}') || true"

