name: deployint to ec2 machine 
on : 
  push :
    branches : 
      - main

jobs : 
    build-backend:
      runs-on : ubuntu-latest
      steps : 
        - uses : actions/checkout@v4
          with:
            fetch-depth : 0
        
        - name: Docker login
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name : Build and push Docker image 
          uses : docker/build-push-action@v4
          with :
            context : .
            file : ./docker/dockerfile.backend
            push : true
            tags : bideshmukhi/backend:${{ github.sha }}
        - run : |
              echo "Deploying backend to ec2 machine"
              echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
              mkdir ~/.ssh
              echo "${{ secrets.KNOWN_HOST }}" &> ~/.ssh/known_hosts
              chmod 700 /home/runner/ssh_key
              ssh  -i ~/ssh_key ubuntu@ec2-3-86-193-29.compute-1.amazonaws.com  "docker stop backend && docker rm backend && docker run -d -p 8080:8080 --name backend bideshmukhi/backend:${{ github.sha }}"
